# C?u hï¿½nh URL k?t n?i ??n MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/AIComic

# Tï¿½n ng??i dï¿½ng MySQL (root)
spring.datasource.username=root

# M?t kh?u cho tï¿½i kho?n root (thay "your_password" b?ng m?t kh?u th?c t? c?a b?n)
spring.datasource.password=@Raizel12345

# Driver s? d?ng ?? k?t n?i MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - JPA c?u hï¿½nh (tï¿½y ch?n, ?? h? tr? ORM)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.forward-headers-strategy=native


# C?u hình Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=717866262643-77vit52fq5r4i29pmpkomtjaq3fv7vu8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

jwt.secret=G4tz1P0L9zKj7DqQz6vF5JfO0rA8pLwWnUyJmXtVYsU=
jwt.expiration=1800000  # 30 phút (tính b?ng milliseconds)


